# docker-compose.yml
version: "3.5"
services:
  app:
    build: .
    networks:
      - vumos
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"

  postgres:
    networks:
      - vumos
    build: db
    environment:
      POSTGRES_PASSWORD: postgres

networks:
  vumos:
    name: vumos
